#pragma once
#include <vector>

const std::vector<const char*> validationLayers = {
	"VK_LAYER_KHRONOS_validation"
};

const std::vector<const char*> deviceRequiredExtensions = {
	VK_KHR_SWAPCHAIN_EXTENSION_NAME,
	VK_KHR_MAINTENANCE1_EXTENSION_NAME,
	VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME,
	VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME
};

#ifndef VK_PIPELINE_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT
#define VK_PIPELINE_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT 0x00000002
#endif